spring:
  application:
    group: examples
    name: example-service
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: example_pool
      maxLifetime: 2000000
      connectionTimeout: 30000
      schema: example
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:example}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  output:
    ansi:
      enabled: always
  jackson:
    default-property-inclusion: non_null

info:
  tags:
    environment: ${spring.profiles.active}
  app:
    name: '@pom.name@'
    description: '@pom.description@'
    version: '@pom.version@'

management:
  auditevents:
    enabled: true
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
      probes:
        enabled: true
      show-details: always
    refresh:
      enabled: true
    restart:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  otlp:
    logging:
      export:
        enabled: false
    metrics:
      export:
        enabled: false
    tracing:
      export:
        enabled: true
      transport: grpc
  server:
    port: 9117
  tracing:
    enabled: true
    sampling:
      probability: 1.0

otel:
  traces:
    exporter: otlp
  logs:
    exporter: none
  metrics:
    exporter: none
